title: 灣區哲學星期五
description: > # this means to ignore newlines until "baseurl:"
  "發源自台北哲學星期五，灣區哲五於2017年10月開辦，邀請在灣區的每位朋友前來一同思索、討論大大小小與你我相關的議題。"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 灣區哲學星期五 # add your name
author-img: logo.png # add your photo
about-author: "發源自台北哲學星期五，灣區哲五於2017年10月開辦，邀請在灣區的每位朋友前來一同思索、討論大大小小與你我相關的議題。" # add description
#twitter: # add your Twitter handle
facebook: CafePhiloAtBayArea # add your Facebook handle
#github: artemsheludko # add your Github handle
#linkedin: # add your Linkedin handle
#email: # add your Email address

# Disqus
discus-identifier: phil5-bay # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
